# http://docs.travis-ci.com/user/languages/r/
language: r

sudo: required

apt_packages:
  - unixodbc-dev

r_github_packages:
  - jimhester/covr
  - zozlak/ZPD
  - zozlak/ZPDzapis

after_success:
  - Rscript -e 'library(covr);coveralls()'
  
notifications:
  email:
    - zozlak@zozlak.org
    - t.zoltak@ibe.edu.pl